package com.senac.daniela.climatecontrol.enums;

public enum Region {
    REGIAO_METROPOLITANA,
    REGIAO_DOS_LAGOS,
    REGIAO_SERRANA,
    REGIAO_NORTE_FLUMINENSE,
    REGIAO_CENTRO_SUL_FLUMINENSE,
    REGIAO_OESTE_FLUMINENSE,
    REGIAO_BAIXADA_FLUMINENSE,
    REGIAO_MEDIO_PARAAIBA
}
